import React from "react";
import { Flex, SimpleGrid, Wrap } from "@chakra-ui/react";
import PillPity from "pill-pity";

export default function Component() {
  const patterns = [
    "jigsaw",
    "overcast",
    "formal-invitation",
    "topography",
    "texture",
    "jupiter",
    "architect",
    "cutout",
    "hideout",
    "graph-paper",
    "yyy",
    "squares",
    "falling-triangles",
    "piano-man",
    "pie-factory",
    "dominos",
    "hexagons",
    "charlie-brown",
    "autumn",
    "temple",
    "stamp-collection",
    "death-star",
    "church-on-sunday",
    "i-like-food",
    "overlapping-hexagons",
    "four-point-stars",
    "bamboo",
    "bathroom-floor",
    "cork-screw",
    "happy-intersection",
    "kiwi",
    "lips",
    "lisbon",
    "random-shapes",
    "steel-beams",
    "tiny-checkers",
    "x-equals",
    "anchors-away",
    "bevel-circle",
    "brick-wall",
    "fancy-rectangles",
    "heavy-rain",
    "overlapping-circles",
    "plus",
    "rounded-plus-connected",
    "volcano-lamp",
    "wiggle",
    "bubbles",
    "cage",
    "connections",
    "current",
    "diagonal-stripes",
    "flipped-diamonds",
    "floating-cogs",
    "glamorous",
    "houndstooth",
    "leaf",
    "lines-in-motion",
    "moroccan",
    "morphing-diamonds",
    "rails",
    "rain",
    "skulls",
    "squares-in-squares",
    "stripes",
    "tic-tac-toe",
    "zig-zag",
    "aztec",
    "bank-note",
    "boxes",
    "circles-squares",
    "circuit-board",
    "curtain",
    "diagonal-lines",
    "endless-clouds",
    "eyes",
    "floor-tile",
    "groovy",
    "intersecting-circles",
    "melt",
    "overlapping-diamonds",
    "parkay-floor",
    "pixel-dots",
    "polka-dots",
    "signal",
    "slanted-stars",
    "wallpaper",
  ];
  return (
    <SimpleGrid columns={[1, 1, 2, 4]} w="full">
      {patterns.map((pattern) => (
        <PillPity pattern={pattern} as={Flex} boxSize="200px">
          {pattern}
        </PillPity>
      ))}
    </SimpleGrid>
  );
}
